#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa

yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

$HOME/.config/yabai/create_spaces.sh

yabai -m config external_bar               all:35:0     \
                window_border              off          \
                mouse_follows_focus        off          \
                focus_follows_mouse        on           \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             off          \
                window_opacity_duration    0.0          \
                active_window_opacity      1.0          \
                normal_window_opacity      0.0          \
                window_border_width        0            \
                window_border_hidpi        off          \
                window_border_radius       11           \
                window_border_blur         off          \
                window_animation_duration  0.3          \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff494d64   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                0            \
                bottom_padding             4            \
                left_padding               4            \
                right_padding              4            \
                window_gap                 6

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|Systemeinstellungen|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m config layout bsp
